python aug_cuda_test_Affine.py
python aug_cuda_test_Blur.py
python aug_cuda_test_Crop.py
python aug_cuda_test_CropAffine.py
python aug_cuda_test_Elastic.py
python aug_cuda_test_Flip.py
python aug_cuda_test_Noise.py
python aug_cuda_test_Norm.py
python aug_cuda_test_Pad.py
python aug_cuda_test_Patches.py
python aug_cuda_test_Resize.py

python aug_cuda_batch_test_Affine.py
python aug_cuda_batch_test_Blur.py
python aug_cuda_batch_test_CropAffine.py
python aug_cuda_batch_test_Elastic.py
python aug_cuda_batch_test_Flip.py
python aug_cuda_batch_test_Noise.py
python aug_cuda_batch_test_Resize.py

python aug_compare.py
python aug_cpu_test_instance.py
python aug_cpu_test_Patches.py

python ops_test_dcn.py
python ops_test_Intensity.py
python ops_test_IoU.py
python ops_test_NMS.py
python ops_test_RoIAlign.py